# EDA PARA RETAIL TRANSACTIONS

In [2]:
import pandas as pd
import numpy as np

In [5]:
# Carga del CSV
ruta = 'C:\\Users\\jairo\\Documents\\Proyectos\\aradiel_25-2\\SI807_Cloud_BI_2025\\grupo10_sutran\\ExFinal\\SolucionIndividual\\DelRio_Gutierrez\\bronce\\Retail_Transactions_Dataset.csv'
df = pd.read_csv(ruta)

## VISUALIZACIÓN Y VISTA GENERAL DE DATOS

In [6]:
print("Shape:", df.shape)
df.head()

Shape: (1000000, 13)

,Transaction_ID,Date,Customer_Name,Product,Total_Items,Total_Cost,Payment_Method,City,Store_Type,Discount_Applied,Customer_Category,Season,Promotion
0,1000000000,2022-01-21 06:27:29,Stacey Price,"['Ketchup', 'Shaving Cream', 'Light Bulbs']",3,71.65,Mobile Payment,Los Angeles,Warehouse Club,True,Homemaker,Winter,NaN
1,1000000001,2023-03-01 13:01:21,Michelle Carlson,"['Ice Cream', 'Milk', 'Olive Oil', 'Bread', 'P...",2,25.93,Cash,San Francisco,Specialty Store,True,Professional,Fall,BOGO (Buy One Get One)
2,1000000002,2024-03-21 15:37:04,Lisa Graves,['Spinach'],6,41.49,Credit Card,Houston,Department Store,True,Professional,Winter,NaN
3,1000000003,2020-10-31 09:59:47,Mrs. Patricia May,"['Tissues', 'Mustard']",1,39.34,Mobile Payment,Chicago,Pharmacy,True,Homemaker,Spring,NaN
4,1000000004,2020-12-10 00:59:59,Susan Mitchell,['Dish Soap'],10,16.42,Debit Card,Houston,Specialty Store,False,Young Adult,Winter,Discount on Selected Items

## TIPO DE DATOS Y VALORES

In [7]:
df.dtypes

Transaction_ID         int64
Date                  object
Customer_Name         object
Product               object
Total_Items            int64
Total_Cost           float64
Payment_Method        object
City                  object
Store_Type            object
Discount_Applied        bool
Customer_Category     object
Season                object
Promotion             object
dtype: object

In [8]:
# Valores nulos
df.isnull().sum()

Transaction_ID            0
Date                      0
Customer_Name             0
Product                   0
Total_Items               0
Total_Cost                0
Payment_Method            0
City                      0
Store_Type                0
Discount_Applied          0
Customer_Category         0
Season                    0
Promotion            333943
dtype: int64

In [9]:
# Valores únicos por columna
df.nunique()

Transaction_ID       1000000
Date                  996337
Customer_Name         329738
Product               571947
Total_Items               10
Total_Cost              9501
Payment_Method             4
City                      10
Store_Type                 6
Discount_Applied           2
Customer_Category          8
Season                     4
Promotion                  2
dtype: int64

In [10]:

# Estadísticas básicas
df.describe(include='all')

,Transaction_ID,Date,Customer_Name,Product,Total_Items,Total_Cost,Payment_Method,City,Store_Type,Discount_Applied,Customer_Category,Season,Promotion
count,1.000000e+06,1000000,1000000,1000000,1000000.000000,1000000.000000,1000000,1000000,1000000,1000000,1000000,1000000,666057
unique,NaN,996337,329738,571947,NaN,NaN,4,10,6,2,8,4,2
top,NaN,2024-03-13 12:44:06,Michael Smith,['Toothpaste'],NaN,NaN,Cash,Boston,Supermarket,True,Senior Citizen,Spring,Discount on Selected Items
freq,NaN,3,454,4893,NaN,NaN,250230,100566,166936,500104,125485,250368,333370
mean,1.000500e+09,NaN,NaN,NaN,5.495941,52.455220,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2.886753e+05,NaN,NaN,NaN,2.871654,27.416989,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000e+09,NaN,NaN,NaN,1.000000,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.000250e+09,NaN,NaN,NaN,3.000000,28.710000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.000500e+09,NaN,NaN,NaN,5.000000,52.420000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000750e+09,NaN,NaN,NaN,8.000000,76.190000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.001000e+09,NaN,NaN,NaN,10.000000,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Ver muestras de columnas clave
print("\nProductos (sample):")
print(df['Product'].sample(5).values)

print("\nMétodos de pago:", df['Payment_Method'].unique())
print("Tiendas:", df['Store_Type'].unique())
print("Temporadas:", df['Season'].unique())

Productos (sample):
["['Dustpan', 'Bath Towels', 'Water', 'Shrimp', 'Toothpaste']"
 "['Plant Fertilizer', 'Salmon', 'Carrots']" "['Hair Gel', 'Soap']"
 "['Beef', 'Shower Gel', 'Tea', 'Eggs']"
 "['Garden Hose', 'Cleaning Spray', 'Dish Soap', 'Orange']"]

Métodos de pago: ['Mobile Payment' 'Cash' 'Credit Card' 'Debit Card']
Tiendas: ['Warehouse Club' 'Specialty Store' 'Department Store' 'Pharmacy'
 'Supermarket' 'Convenience Store']
Temporadas: ['Winter' 'Fall' 'Spring' 'Summer']